export const details_fields = [
  {
    icon: 'nature-people',
    type: 'material',
    icon_color: '#22E42A',
    title: 'Population',
    data: 'population',
  },
  {
    icon: 'percent',
    type: 'font-awesome',
    icon_color: 'yellow',
    title: '% Infected',
    data: 'population',
  },
  {
    icon: 'hospital-o',
    type: 'font-awesome',
    icon_color: 'red',
    title: 'Critical Cases',
    data: 'critical',
  },
  {
    icon: 'stethoscope',
    type: 'font-awesome',
    icon_color: 'orange',
    title: 'Total Tests',
    data: 'tests',
  },
  {
    icon: 'coronavirus',
    type: 'material',
    icon_color: 'yellow',
    title: 'Cases Per Million',
    data: 'casesPerOneMillion',
  },
  {
    icon: 'skull-outline',
    type: 'ionicon',
    icon_color: 'red',
    title: 'Deaths Per Million',
    data: 'deathsPerOneMillion',
  },
  {
    icon: 'pie-chart',
    type: 'material',
    icon_color: 'orange',
    title: 'Tests Per Million',
    data: 'testsPerOneMillion',
  },
  {
    icon: 'supervisor-account',
    type: 'material',
    icon_color: 'purple',
    title: 'Active cases Per Million',
    data: 'activePerOneMillion',
  },
  {
    icon: 'local-hospital',
    type: 'material',
    icon_color: 'green',
    title: 'Recovered cases Per Million',
    data: 'recoveredPerOneMillion',
  },
  {
    icon: 'local-hotel',
    type: 'material',
    icon_color: 'pink',
    title: 'Critical cases Per Million',
    data: 'criticalPerOneMillion',
  },
];
